# Goal - I hae to lint, build, test the code for frontend and backend
# then push the images to docker hub

name: CI

on:
    push:
        branches: [advanced]

jobs:    

    frontend:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout code
            uses: actions/checkout@v7

        -   name: Setup Nodejs
            uses: actions/setup-node@v6
            with:
                node-version: '20'
                cache: npm
                cache-dependency-path: devboard-project\frontend\package-lock.json

        -       name: Install npm packages
                run : npm ci

        -       name: Run Linter
                run : npm run lint

        -       name: Run tests
                run : npm run test
                
                # backend: