# Goal: To run and end to end DevSecOps CI pipeline

name: DevSecOps

on:
    push:
        branches: [main]

jobs:


    code-quality:
        uses: ./.github/workflows/code-quality.yml

    secret-scanning:
        uses: ./.github/workflows/secret-scanning.yml

    dependency-scanning:
        uses: ./.github/workflows/dependency-scan.yml

    docker-checks:
        uses: ./.github/workflows/docker-scan.yml
        secrets: inherit

    sonar-scanning:
        uses: ./.github/workflows/sonar-scan.yml
        secrets: inherit

    code-test:
        uses: ./.github/workflows/code-test.yml

    docker-push:
        uses: ./.github/workflows/docker-push.yml
        needs: [code-test,sonar-scanning,docker-checks,dependency-scanning,secret-scanning,code-quality]
        secrets: inherit